[package]
name = "postgresql_connection"
version = "0.1.7"
edition = "2021"

[dependencies]
time = { git = "https://github.com/jeffersoncbd/time.git" }
dotenvy = "0.15.7"
sqlx = { version = "0.8.3", features = ["postgres", "macros", "runtime-tokio-native-tls", "time"] }
